### ISSUE TITLE
`add_row` payload too large?

### ISSUE THREAD

**Issue by jean** [jamalex/notion-py#111]
Has anyone seen this? `add_row` has more or less suddenly started failing. 

```
Traceback (most recent call last):
  File "server.py", line 94, in <module>
    row = IMPORTED_ISSUES.collection.add_row()
  File "/app/.data/venv/lib/python3.7/site-packages/notion/collection.py", line 156, in add_row
    view.set("page_sort", view.get("page_sort", []) + [row_id])
  File "/app/.data/venv/lib/python3.7/site-packages/notion/client.py", line 325, in __exit__
    self.client.submit_transaction(operations)
  File "/app/.data/venv/lib/python3.7/site-packages/notion/client.py", line 213, in submit_transaction
    self.post("submitTransaction", data)
  File "/app/.data/venv/lib/python3.7/site-packages/notion/client.py", line 188, in post
    response.raise_for_status()
  File "/app/.data/venv/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 413 Client Error: Payload Too Large for url: https://www.notion.so/api/v3/submitTransaction
```

**Comment by jean** [comment]
OK, this is because all the ids of the rows in each view is sent with an `add_row` call. 
It looks like this is happening even if the view is filtered (view `1-2-3-4-5` is filtered to 700+ rows, but it's sending the entire 11601 row ids).

Logging `operations` in `notion/client.py`, line 213, in `submit_transaction`
    `self.post("submitTransaction", data)`

```
id 1-2-3-4-5
path ['page_sort']
args 11601
command set
table collection_view

id 1-2-3-4-6
path ['page_sort']
args 726
command set
table collection_view

id 1-2-3-4-7
path ['page_sort']
args 232
command set
table collection_view

id 1-2-3-4-8
path ['page_sort']
args 142
command set
table collection_view

id 1-2-3-4-9
path ['page_sort']
args 42
command set
table collection_view

id 1-2-3-4-10
path ['page_sort']
args 42
command set
table collection_view
```

**Comment by jean** [comment]
And this is happening because of _making sure the record is inserted at the end of each view_ ... what goes wrong if we don't do this? 

```python
              # make sure the new record is inserted at the end of each view                                                                                                                                                           
              for view in self.parent.views:                                                                                                                                                                                           
                  if isinstance(view, CalendarView):                                                                                                                                                                                   
                      continue                                                                                                                                                                                                         
                  view.set("page_sort", view.get("page_sort", []) + [row_id])                                                                                                                                                          
```

**Comment by ftomassetti** [comment]
Same here. Any workaround?

**Comment by jean** [comment]
@ftomassetti https://github.com/jamalex/notion-py/pull/112

**Comment by ftomassetti** [comment]
Yes, it was super useful! Thank you!
