### ISSUE TITLE
API Timeout

### ISSUE THREAD

**Issue by odusseys** [jamalex/notion-py#223]
I am occasionally getting API timeouts (504 gateway errors) from Notion using the client. For obvious reasons, it is going to be tough to provide a reproducible example.
Is there a way to configure the client to retry in such an event ?

**Comment by jamalex** [comment]
Could you provide a traceback, so we can see where it's happening? (To help
with planning where a handler would go). Thanks!

**Comment by EolianPipes** [comment]
I've been running into this recently as well. I'll try to paste the traceback the next time I run into it.

**Comment by Cyberpuncrush** [comment]
> Could you provide a traceback, so we can see where it's happening? (To help with planning where a handler would go). Thanks!
> […](#)

Same issue, traceback:

python3 /home/realcrush/zotero2notion.py
Traceback (most recent call last):
  File "/home/realcrush/zotero2notion.py", line 83, in <module>
    client = NotionClient(token_v2=token_v2)
  File "/home/realcrush/anaconda3/lib/python3.8/site-packages/notion/client.py", line 68, in __init__
    self._update_user_info()
  File "/home/realcrush/anaconda3/lib/python3.8/site-packages/notion/client.py", line 74, in _update_user_info
    records = self.post("loadUserContent", {}).json()["recordMap"]
  File "/home/realcrush/anaconda3/lib/python3.8/site-packages/notion/client.py", line 188, in post
    response.raise_for_status()
  File "/home/realcrush/anaconda3/lib/python3.8/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 504 Server Error: Gateway Time-out for url: https://www.notion.so/api/v3/loadUserContent

**Comment by odusseys** [comment]
Getting this increasingly often when crawling large Notion workspaces. I'm guessing it's either random or some kind of poor man's rate limiting - either way I think I'll be forking to handle the error & retry w/ exponential backoff ; may open a PR if I do so.
