### ISSUE TITLE
Error when accessing "non-shared-to-web" document.

### ISSUE THREAD

**Issue by ngmiduc** [jamalex/notion-py#224]
Concerning issue : #202 [private-documents] use notion-py without "share to the web"

````
Hi,
I would like to know if this is also working without having the page "share to the web" via link.
I thought when I add my token it doesn't need to be a "public" page.
```

I receiving this error message when I deactivate the "share-to-web" option of the demanded page in Notion.
I have deployed a Heroku python server to use notion-py. When I make the page public again, everything works fine. I added the right token to the application.



Logs from heroku when accessing notion data via notion-py: 
```
2020-11-24T10:08:01.772448+00:00 app[web.1]: return self.view_functions[rule.endpoint](**req.view_args)
2020-11-24T10:08:01.772449+00:00 app[web.1]: File "/app/app/main.py", line 28, in api_calendar
2020-11-24T10:08:01.772449+00:00 app[web.1]: data = client.get_collection_view(DATABASE)
2020-11-24T10:08:01.772449+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/notion/client.py", line 139, in get_collection_view
2020-11-24T10:08:01.772450+00:00 app[web.1]: collection = self.get_block(
2020-11-24T10:08:01.772450+00:00 app[web.1]: AttributeError: 'NoneType' object has no attribute 'collection'
```

**Comment by nwittwer** [comment]
I'm seeing this now as well. It was working with private Notion databases before the Nov. 22, 2020 Notion update using v0.0.27 of `notion-py` library.

Log:
```bash
Traceback (most recent call last):
  File ".../scripts/notion-to-excel.py", line 28, in <module>
    cv = client.get_collection_view(NOTION-DATABASE-URL)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/notion/client.py", line 165, in get_collection_view
    collection = self.get_block(
AttributeError: 'NoneType' object has no attribute 'collection'
```

**Comment by ngmiduc** [comment]
Looks like a bug in the new version. Is there a version where that is working? 
Did anyone try with an older version?
