### ISSUE TITLE
Unresponsive and repeat file changes at running code

### ISSUE THREAD

**Issue by seonggwonyoon** [jamalex/notion-py#24]
If you attempt to fetch information using `get_block`, `get_collection_view` on a Specific full page, the code will not work and will remain stuck.
And `****_values.json`, `****_role.json` in the `~/.notion-py/cache` folder are changed from time to time.

PS. The specific page type is Database and Full-Page, and more than 5000 internal items

How can I fix it?

### Using get_block(page_url)
![get_block](https://user-images.githubusercontent.com/37574822/57355600-55898b80-71a9-11e9-8611-9c04b29c47ec.gif)

### Using get_collection_view(page_url)
![get_collection](https://user-images.githubusercontent.com/37574822/57355625-676b2e80-71a9-11e9-8784-f4de0fc73f80.gif)

But collection_view is return None

You can not see that `****_role.json` changes in the picture, but sometimes this file is changed like the `****_values.json` file.

Add the information below.

### pip list
---
```bash
$ pip list
notion          0.0.21
pip             19.1.1
python-slugify  3.0.2
pytz            2019.1
requests        2.21.0
setuptools      41.0.1
soupsieve       1.9.1
text-unidecode  1.2
tzlocal         2.0.0b1
urllib3         1.24.3
wheel           0.33.1
```

### Code
---
```python
from notion.client import NotionClient

client = NotionClient(token_v2="blank")
page = client.get_collection("blank") # return None
# page = client.get_collection_view("blank") not response
# page = client.get_block("blank") not response

print(page)
```

If force shutdown while stopped, the following error appears.

### Running at get_block
---
```
^CTraceback (most recent call last):
  File "main.py", line 7, in <module>
    print(page)
  File "/Users/ted/Workspace/tmp/notion-py/venv/lib/python3.7/site-packages/notion-0.0.21-py3.7.egg/notion/records.py", line 35, in __str__
    return ", ".join(["{}={}".format(field, repr(getattr(self, field))) for field in self._str_fields() if getattr(self, field, "")])
  File "/Users/ted/Workspace/tmp/notion-py/venv/lib/python3.7/site-packages/notion-0.0.21-py3.7.egg/notion/records.py", line 35, in <listcomp>
    return ", ".join(["{}={}".format(field, repr(getattr(self, field))) for field in self._str_fields() if getattr(self, field, "")])
  File "/Users/ted/Workspace/tmp/notion-py/venv/lib/python3.7/site-packages/notion-0.0.21-py3.7.egg/notion/block.py", line 634, in title
    return self.collection.name
  File "/Users/ted/Workspace/tmp/notion-py/venv/lib/python3.7/site-packages/cached_property-1.5.1-py3.7.egg/cached_property.py", line 35, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/Users/ted/Workspace/tmp/notion-py/venv/lib/python3.7/site-packages/notion-0.0.21-py3.7.egg/notion/block.py", line 623, in collection
    self._collection = self._client.get_collection(collection_id)
  File "/Users/ted/Workspace/tmp/notion-py/venv/lib/python3.7/site-packages/notion-0.0.21-py3.7.egg/notion/client.py", line 73, in get_collection
    return Collection(self, collection_id) if coll else None
  File "/Users/ted/Workspace/tmp/notion-py/venv/lib/python3.7/site-packages/notion-0.0.21-py3.7.egg/notion/collection.py", line 104, in __init__
    self._client.refresh_collection_rows(self.id)
  File "/Users/ted/Workspace/tmp/notion-py/venv/lib/python3.7/site-packages/notion-0.0.21-py3.7.egg/notion/client.py", line 118, in refresh_collection_rows
    row_ids = self.search_pages_with_parent(collection_id)
  File "/Users/ted/Workspace/tmp/notion-py/venv/lib/python3.7/site-packages/notion-0.0.21-py3.7.egg/notion/client.py", line 174, in search_pages_with_parent
    self._store.store_recordmap(response["recordMap"])
  File "/Users/ted/Workspace/tmp/notion-py/venv/lib/python3.7/site-packages/notion-0.0.21-py3.7.egg/notion/store.py", line 237, in store_recordmap
    self._update_record(table, id, value=record.get("value"), role=record.get("role"))
  File "/Users/ted/Workspace/tmp/notion-py/venv/lib/python3.7/site-packages/notion-0.0.21-py3.7.egg/notion/store.py", line 176, in _update_record
    self._save_cache("_values")
  File "/Users/ted/Workspace/tmp/notion-py/venv/lib/python3.7/site-packages/notion-0.0.21-py3.7.egg/notion/store.py", line 139, in _save_cache
    json.dump(getattr(self, attribute), f)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 180, in dump
    fp.write(chunk)
KeyboardInterrupt
```

### Running at get_collection_view
---
```
^CTraceback (most recent call last):
  File "main.py", line 4, in <module>
    page = client.get_collection_view("blank")
  File "/Users/ted/Workspace/tmp/notion-py/venv/lib/python3.7/site-packages/notion-0.0.21-py3.7.egg/notion/client.py", line 101, in get_collection_view
    collection = self.get_block(block_id, force_refresh=force_refresh).collection
  File "/Users/ted/Workspace/tmp/notion-py/venv/lib/python3.7/site-packages/cached_property-1.5.1-py3.7.egg/cached_property.py", line 35, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/Users/ted/Workspace/tmp/notion-py/venv/lib/python3.7/site-packages/notion-0.0.21-py3.7.egg/notion/block.py", line 623, in collection
    self._collection = self._client.get_collection(collection_id)
  File "/Users/ted/Workspace/tmp/notion-py/venv/lib/python3.7/site-packages/notion-0.0.21-py3.7.egg/notion/client.py", line 73, in get_collection
    return Collection(self, collection_id) if coll else None
  File "/Users/ted/Workspace/tmp/notion-py/venv/lib/python3.7/site-packages/notion-0.0.21-py3.7.egg/notion/collection.py", line 104, in __init__
    self._client.refresh_collection_rows(self.id)
  File "/Users/ted/Workspace/tmp/notion-py/venv/lib/python3.7/site-packages/notion-0.0.21-py3.7.egg/notion/client.py", line 118, in refresh_collection_rows
    row_ids = self.search_pages_with_parent(collection_id)
  File "/Users/ted/Workspace/tmp/notion-py/venv/lib/python3.7/site-packages/notion-0.0.21-py3.7.egg/notion/client.py", line 174, in search_pages_with_parent
    self._store.store_recordmap(response["recordMap"])
  File "/Users/ted/Workspace/tmp/notion-py/venv/lib/python3.7/site-packages/notion-0.0.21-py3.7.egg/notion/store.py", line 237, in store_recordmap
    self._update_record(table, id, value=record.get("value"), role=record.get("role"))
  File "/Users/ted/Workspace/tmp/notion-py/venv/lib/python3.7/site-packages/notion-0.0.21-py3.7.egg/notion/store.py", line 166, in _update_record
    with self._mutex:
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/synchronize.py", line 95, in __enter__
    return self._semlock.__enter__()
KeyboardInterrupt
```

**Comment by jamalex** [comment]
Thanks for reporting. Does it work for you on a similar database page with fewer rows? It's possible it's taking a long time to enumerate the large DB.

More generally, in terms of performance, there are a couple of things indicated by this:
- We should update the disk cache data files on a less frequent basis (e.g. a separate thread checking and writing on an interval, rather then every time a change happens).
- We should probably use a more efficient disk cache data structure to start with.
- Part of what is making it slow is populating the data for all the database rows. Perhaps some of this could be made "lazy"...

**Comment by jamalex** [comment]
As of 0.0.25 (just released) the disk cache is now disabled by default, and can be enabled with `NotionClient(..., enable_caching=True)`.
