### ISSUE TITLE
get_collection_view() return error 400, unless it's favorited

### ISSUE THREAD

**Issue by teenphly** [jamalex/notion-py#299]
Hi, I'm new to python and notion-py, and just get started. Today, I tried:
`from notion.client import NotionClient

token = <my token>
url = <url to my database>
client = NotionClient(token_v2=token)
cv = client.get_collection_view(url)`

and it gave me:
`Traceback (most recent call last):
  File "test.py", line 7, in <module>
    cv = client.get_collection_view(url)
  File "/home/theo/.local/lib/python3.6/site-packages/notion/client.py", line 217, in get_collection_view
    block_id, force_refresh=force_refresh
  File "/home/theo/.local/lib/python3.6/site-packages/notion/client.py", line 169, in get_block
    block = self.get_record_data("block", block_id, force_refresh=force_refresh)
  File "/home/theo/.local/lib/python3.6/site-packages/notion/client.py", line 162, in get_record_data
    return self._store.get(table, id, force_refresh=force_refresh)
  File "/home/theo/.local/lib/python3.6/site-packages/notion/store.py", line 184, in get
    self.call_load_page_chunk(id)
  File "/home/theo/.local/lib/python3.6/site-packages/notion/store.py", line 286, in call_load_page_chunk
    recordmap = self._client.post("loadPageChunk", data).json()["recordMap"]
  File "/home/theo/.local/lib/python3.6/site-packages/notion/client.py", line 262, in post
    "message", "There was an error (400) submitting the request."
requests.exceptions.HTTPError: Invalid input.`

I can access any page by get_block() normally, and finally get the collection view, but that would be troublesome. And when I favorite the database, it works just fine, I can get the collection view directly! I wonder what I'm doing wrong.

**Comment by herberthamaral** [comment]
Looks like notion has changed its API. I used the `get_collection_view` method a few weeks ago with no issues. I executed the same code today and I got the `Invalid input.` error.

**Comment by RenanBomtempo** [comment]
> Looks like notion has changed its API. I used the `get_collection_view` method a few weeks ago with no issues. I executed the same code today and I got the `Invalid input.` error.

I'm experiencing the exact same thing.
