### ISSUE TITLE
how to get page block notion

### ISSUE THREAD

**Issue by byndstd** [jamalex/notion-py#303]
I'm trying to get a notion page block using notion.py but I didn't succeed my code is 
```
from notion.client import NotionClient
import time

# Log in
token_v2 = "The_Token_Number"
client = NotionClient(token_v2 = token_v2)

# Connection to the page

## The page to read
list_url_read = 'https://www.url_of_the_page_1'

page_read = client.get_block(list_url_read)
### collection_read = client.collection.collection_view(list_url_read)


## The page to post
list_url_post = 'https://www.url_of_the_page_2'

### page_post = client.get_block(list_url_post)
collection_post = client.get_collection_view(list_url_post) 

## Insert In page read
new_row = collection_post.collection.add_row()
new_row.title = page_read.title
new_row.status = page_read.status
```

The page one that I want to get it's block value is :
[https://i.stack.imgur.com/LFqM0.png](url)

**Comment by byndstd** [comment]
anyone can help 
please?

**Comment by kamikazebr** [comment]
Try give us more information, which errors occours? Post some logs and etc. Maybe so more people can help you.

**Comment by byndstd** [comment]
> Try give us more information, which errors occours? Post some logs and etc. Maybe so more people can help you.

this the error
```
lotfi@Lenovo:~/dprojects/pyt$ python3 auto_notion_read.py 
Traceback (most recent call last):
  File "auto_notion_read.py", line 19, in <module>
    collection_read = client.get_collection_rows(list_url_read)
AttributeError: 'NotionClient' object has no attribute 'get_collection_rows'
```

**Comment by byndstd** [comment]
> @byndstd your line comment out is different from the error
> 
> `### collection_read = client.collection.collection_view(list_url_read)`
> 
> Anyway the method `get_collection_rows` its from `client._store` its not public acess, you can check that copy and paste the name in search box of git repository.
> 
> And check the documentation in the start page looking for that method.
> 
> https://github.com/jamalex/notion-py#example-working-with-databases-aka-collections-tables-boards-etc
> ![image](https://user-images.githubusercontent.com/691510/115768325-8a844e00-a380-11eb-939f-3cf5712ea594.png)
> 
> Its probaly what you want
> 
> ```
> 
> cv = client.get_collection_view("https://www.notion.so/myorg/8511b9fc522249f79b90768b832599cc?v=8dee2a54f6b64cb296c83328adba78e1")
> 
> # List all the records with "Bob" in them
> for row in cv.collection.get_rows(search="Bob"):
> ```
> 
> Check that and hope it can help you

I didn't work
I post the code and error 

```
from notion.client import NotionClient
import time

# Log in
token_v2 = "7a87239c3c4410a7def4b9398678f43b9df4ea11a925921bafadd2b91f3ce9d01e5fba091b2e4a4628e98c1c8aae6e3f1ec89724b243f8f63e6cc3d035e1e5425f4d8584cedd5a431755c25eabcb"
client = NotionClient(token_v2 = token_v2)

# Connection to the page

## The page to read
list_url_read = 'https://www.notion.so/nixamtl/CQTS-Validation-des-donn-es-du-dashboard-cf257eb79e674c09a8d58df7017d0b10'

collection_read = client.get_collection_view(list_url_read)

for row in collection_read.collection.get_rows(search="Bob"):
    print("We estimate the value of '{}' at {}".format(row.name, row.estimated_value))

## The page to post
list_url_post = 'https://www.notion.so/nixamtl/24aabbe33f40472c86652a4603aeb345?v=f1776366c6584c79bcd8d26ec33451ae'

collection_post = client.get_collection_view(list_url_post)
```
The error is
```
lotfi@Lenovo:~/dprojects/pyt$ python3 auto_notion_read.py 
Traceback (most recent call last):
  File "auto_notion_read.py", line 16, in <module>
    collection_read = client.get_collection_view(list_url_read)
  File "/home/lotfi/.local/lib/python3.6/site-packages/notion/client.py", line 214, in get_collection_view
    raise Exception("Invalid collection view URL")
Exception: Invalid collection view URL
lotfi@Lenovo:~/dprojects/pyt$
```
