### ISSUE TITLE
SSL Validation Failure

### ISSUE THREAD

**Issue by stevenbuehler** [jamalex/notion-py#332]
```
Traceback (most recent call last):
  File "C:\Users\s4b4211\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\s4b4211\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 382, in _make_request  
    self._validate_conn(conn)
  File "C:\Users\s4b4211\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "C:\Users\s4b4211\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connection.py", line 411, in connect
    self.sock = ssl_wrap_socket(
  File "C:\Users\s4b4211\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\util\ssl_.py", line 428, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "C:\Users\s4b4211\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\util\ssl_.py", line 472, in _ssl_wrap_socket_impl   
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "C:\Users\s4b4211\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Users\s4b4211\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1040, in _create
    self.do_handshake()
  File "C:\Users\s4b4211\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\s4b4211\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "C:\Users\s4b4211\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 783, in urlopen
    return self.urlopen(
  File "C:\Users\s4b4211\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 783, in urlopen
    return self.urlopen(
  File "C:\Users\s4b4211\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 783, in urlopen
    return self.urlopen(
  [Previous line repeated 2 more times]
  File "C:\Users\s4b4211\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "C:\Users\s4b4211\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\util\retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.notion.so', port=443): Max retries exceeded with url: /api/v3/loadUserContent (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "s:\Settlement Reporting\Scripts\Powershell Scripts\Email_to_Notion.py", line 4, in <module>
    client = NotionClient(token_v2='9e4e763f1b4d5d44a5e942dd3060ffa065ea418023dd01701ee5e594612b7509e15e6f08432fb60e4bc8659f91f94e0f6a3ca72fdf7f667bbeed39883d8bfeff92f71f705508ba14c18422a3e0d3')
  File "C:\Users\s4b4211\AppData\Local\Programs\Python\Python39\lib\site-packages\notion\client.py", line 95, in __init__
    self._update_user_info()
  File "C:\Users\s4b4211\AppData\Local\Programs\Python\Python39\lib\site-packages\notion\client.py", line 126, in _update_user_info
    records = self.post("loadUserContent", {}).json()["recordMap"]
  File "C:\Users\s4b4211\AppData\Local\Programs\Python\Python39\lib\site-packages\notion\client.py", line 253, in post
    response = self.session.post(url, json=data)
  File "C:\Users\s4b4211\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 590, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "C:\Users\s4b4211\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\s4b4211\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\s4b4211\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='www.notion.so', port=443): Max retries exceeded with url: /api/v3/loadUserContent (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)')))
```

**Comment by bedge** [comment]
I'm seeing the same thing.
Just getting started on the API and assuming I'm doing something stupid, as usual.
- notion==0.0.28
- python=3.9.0
```
Python 3.9.0 (default, Dec  9 2020, 10:07:40)
[Clang 12.0.0 (clang-1200.0.32.27)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from notion.client import NotionClient
>>> import os
>>> client = NotionClient(token_v2=os.getenv(NOTION_TOKEN))
Traceback (most recent call last):
  File "/Users/edgeb1/.pyenv/versions/3.9.0/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/Users/edgeb1/.pyenv/versions/3.9.0/lib/python3.9/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/Users/edgeb1/.pyenv/versions/3.9.0/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1040, in _validate_conn
    conn.connect()
  File "/Users/edgeb1/.pyenv/versions/3.9.0/lib/python3.9/site-packages/urllib3/connection.py", line 416, in connect
    self.sock = ssl_wrap_socket(
  File "/Users/edgeb1/.pyenv/versions/3.9.0/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/Users/edgeb1/.pyenv/versions/3.9.0/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/Users/edgeb1/.pyenv/versions/3.9.0/lib/python3.9/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/Users/edgeb1/.pyenv/versions/3.9.0/lib/python3.9/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/Users/edgeb1/.pyenv/versions/3.9.0/lib/python3.9/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1122)
```
