### ISSUE TITLE
Help!!! requests.exceptions.HTTPError: Invalid input.

### ISSUE THREAD

**Issue by Vencent-Won** [jamalex/notion-py#385]
Sorry to disturb you. When I try the example code.
client = NotionClient(token_v2="<token_v2>")
page = client.get_block("<page>")

Then, it came out the error that:
Traceback (most recent call last):
  File "D:\program files\JetBrains\PyCharm 2021.3.2\plugins\python\helpers\pydev\pydevd.py", line 1483, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "D:\program files\JetBrains\PyCharm 2021.3.2\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "D:/Users/Vencent-Won/PycharmProjects/mark2notion/main.py", line 9, in <module>
    page = client.get_block("https://www.notion.so/Paper-Reading-Notes-2d79e4bcb83b4c22a7e054cd9bb6634a")
  File "C:\Users\Vencent-Won\AppData\Roaming\Python\Python37\site-packages\notion\client.py", line 169, in get_block
    block = self.get_record_data("block", block_id, force_refresh=force_refresh)
  File "C:\Users\Vencent-Won\AppData\Roaming\Python\Python37\site-packages\notion\client.py", line 162, in get_record_data
    return self._store.get(table, id, force_refresh=force_refresh)
  File "C:\Users\Vencent-Won\AppData\Roaming\Python\Python37\site-packages\notion\store.py", line 184, in get
    self.call_load_page_chunk(id)
  File "C:\Users\Vencent-Won\AppData\Roaming\Python\Python37\site-packages\notion\store.py", line 286, in call_load_page_chunk
    recordmap = self._client.post("loadPageChunk", data).json()["recordMap"]
  File "C:\Users\Vencent-Won\AppData\Roaming\Python\Python37\site-packages\notion\client.py", line 262, in post
    "message", "There was an error (400) submitting the request."
requests.exceptions.HTTPError: Invalid input.

**Comment by yxyx724** [comment]
I had the same issue.

**Comment by JorgeHI** [comment]
Same issue here, any solution?

**Comment by Mogby** [comment]
Found solution here: https://github.com/paperboi/kindle2notion/issues/14

**Comment by quiri86** [comment]
Didn't work for me, line 280 seems to have been amended in the package alraedy

**Comment by everyoneloveme1** [comment]
> Found solution here: [paperboi/kindle2notion#14](https://github.com/paperboi/kindle2notion/issues/14)

it works!!!!  thank you !
