### ISSUE TITLE
RecursionError on polling and operations

### ISSUE THREAD

**Issue by bkiac** [jamalex/notion-py#58]
```python
Traceback (most recent call last):
  File "C:\Users\Bence\.virtualenvs\wickie-Qv0iMXBj\lib\site-packages\notion\monitor.py", line 241, in poll_forever
    self.poll()
  File "C:\Users\Bence\.virtualenvs\wickie-Qv0iMXBj\lib\site-packages\notion\monitor.py", line 162, in poll
    self.poll(retries=retries - 1)
  File "C:\Users\Bence\.virtualenvs\wickie-Qv0iMXBj\lib\site-packages\notion\monitor.py", line 162, in poll
    self.poll(retries=retries - 1)
  File "C:\Users\Bence\.virtualenvs\wickie-Qv0iMXBj\lib\site-packages\notion\monitor.py", line 162, in poll
    self.poll(retries=retries - 1)
  [Previous line repeated 3 more times]
  File "C:\Users\Bence\.virtualenvs\wickie-Qv0iMXBj\lib\site-packages\notion\monitor.py", line 165, in poll
    self._decode_numbered_json_thing(response.content)
  File "C:\Users\Bence\.virtualenvs\wickie-Qv0iMXBj\lib\site-packages\notion\monitor.py", line 218, in _refresh_updated_records
    self.client.refresh_collection_rows(collection_id)
  File "C:\Users\Bence\.virtualenvs\wickie-Qv0iMXBj\lib\site-packages\notion\client.py", line 141, in refresh_collection_rows
    row_ids = self.search_pages_with_parent(collection_id)
  File "C:\Users\Bence\.virtualenvs\wickie-Qv0iMXBj\lib\site-packages\notion\client.py", line 213, in search_pages_with_parent
    self._store.store_recordmap(response["recordMap"])
  File "C:\Users\Bence\.virtualenvs\wickie-Qv0iMXBj\lib\site-packages\notion\store.py", line 292, in store_recordmap
    table, id, value=record.get("value"), role=record.get("role")
  File "C:\Users\Bence\.virtualenvs\wickie-Qv0iMXBj\lib\site-packages\notion\store.py", line 207, in _update_record
    expand=True,
  File "C:\Users\Bence\.virtualenvs\wickie-Qv0iMXBj\lib\site-packages\dictdiffer\__init__.py", line 217, in _diff_recursive
    for diffed in recurred:
  File "C:\Users\Bence\.virtualenvs\wickie-Qv0iMXBj\lib\site-packages\dictdiffer\__init__.py", line 217, in _diff_recursive
    for diffed in recurred:
  File "C:\Users\Bence\.virtualenvs\wickie-Qv0iMXBj\lib\site-packages\dictdiffer\__init__.py", line 217, in _diff_recursive
    for diffed in recurred:
  File "C:\Users\Bence\.virtualenvs\wickie-Qv0iMXBj\lib\site-packages\dictdiffer\__init__.py", line 264, in _diff_recursive
    (key, deepcopy(_first[key]))]
  File "C:\Users\Bence\.virtualenvs\wickie-Qv0iMXBj\lib\copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "C:\Users\Bence\.virtualenvs\wickie-Qv0iMXBj\lib\copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "C:\Users\Bence\.virtualenvs\wickie-Qv0iMXBj\lib\copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "C:\Users\Bence\.virtualenvs\wickie-Qv0iMXBj\lib\copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "C:\Users\Bence\.virtualenvs\wickie-Qv0iMXBj\lib\copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "C:\Users\Bence\.virtualenvs\wickie-Qv0iMXBj\lib\copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "C:\Users\Bence\.virtualenvs\wickie-Qv0iMXBj\lib\copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "C:\Users\Bence\.virtualenvs\wickie-Qv0iMXBj\lib\copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "C:\Users\Bence\.virtualenvs\wickie-Qv0iMXBj\lib\copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "C:\Users\Bence\.virtualenvs\wickie-Qv0iMXBj\lib\copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "C:\Users\Bence\.virtualenvs\wickie-Qv0iMXBj\lib\copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "C:\Users\Bence\.virtualenvs\wickie-Qv0iMXBj\lib\copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "C:\Users\Bence\.virtualenvs\wickie-Qv0iMXBj\lib\copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "C:\Users\Bence\.virtualenvs\wickie-Qv0iMXBj\lib\copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "C:\Users\Bence\.virtualenvs\wickie-Qv0iMXBj\lib\copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "C:\Users\Bence\.virtualenvs\wickie-Qv0iMXBj\lib\copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "C:\Users\Bence\.virtualenvs\wickie-Qv0iMXBj\lib\copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "C:\Users\Bence\.virtualenvs\wickie-Qv0iMXBj\lib\copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "C:\Users\Bence\.virtualenvs\wickie-Qv0iMXBj\lib\copy.py", line 141, in deepcopy
    d = id(x)
RecursionError: maximum recursion depth exceeded while calling a Python object
```
I get this error every time the monitor tries to poll, or I set a variable. Setting a variable eventually raises a `RecursionError` inside `run_local_operation`.

**Comment by jamalex** [comment]
Thanks for opening the issue! I haven't been able to replicate this, but monitoring is currently broken at the moment due to some changes on the notion.so side. If this is still happening in a future version once monitoring is working again, please re-open and share some replication code, and we can try to get to the bottom of it (hah, recursion pun). Thanks!
