### ISSUE TITLE
Android Termux: "ImportError: cannot import name 'SemLock' from '_multiprocessing'"

### ISSUE THREAD

**Issue by h00rj** [jamalex/notion-py#61]
Not so much an issue as a request.
I have it running perfectly on raspberry pi, it's awesome!

I'm a huge fan of Tasker on Android, and there's a terminal emulator for Android that works well with Tasker that can run python scripts called Termux, however, when I attempt to run notion-py I get this error:

```
>>> from notion.client import NotionClient              
>>> client = NotionClient(token_v2="AlmostForgotToTakeOutMyTokenHeh")
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.7/multiprocessing/synchronize.py", line 28, in <module>
    from _multiprocessing import SemLock, sem_unlink
ImportError: cannot import name 'SemLock' from '_multiprocessing' (/data/data/com.termux/files/usr/lib/python3.7/lib-dynload/_multiprocessing.cpython-37m.so)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/notion/client.py", line 39, in __init__
    self._store = RecordStore(self, cache_key=cache_key)
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/notion/store.py", line 78, in __init__
    self._mutex = Lock()
  File "/data/data/com.termux/files/usr/lib/python3.7/multiprocessing/context.py", line 66, in Lock
    from .synchronize import Lock
  File "/data/data/com.termux/files/usr/lib/python3.7/multiprocessing/synchronize.py", line 32, in <module>
    " synchronization primitives needed will not" +
ImportError: This platform lacks a functioning sem_open implementation, therefore, the required synchronization primitives needed will not function, see issue 3770.
```

I've found a similar issue on a different project that may have a solution, but it requires changing the code.  I fear I'm not adept enough with Python to make these changes to your script... 
Here's the link to the other issue 
https://github.com/asciinema/asciinema/issues/271

I'll keep digging, but I appreciate any help.  It would be phenomenal to have this script running on Android.

**Comment by jamalex** [comment]
Fixed in #67
